name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/calling_rate_r --tag islasgeci/calling_rate_r:${GITHUB_SHA:0:4} . 
    - name: Verifica el formato
      run: docker run islasgeci make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci make coverage
    - name: Corre mutation testing
      run: docker run islasgeci make mutants
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/calling_rate_r:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/calling_rate_r:${GITHUB_SHA:0:4}
